/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthRoleRouteImport } from './routes/auth.role'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthFaceRouteImport } from './routes/auth.face'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppQualityRouteImport } from './routes/app.quality'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMaintenanceRouteImport } from './routes/app.maintenance'
import { Route as AppLessonsRouteImport } from './routes/app.lessons'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppInsuranceRouteImport } from './routes/app.insurance'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppGraphRouteImport } from './routes/app.graph'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCopilotRouteImport } from './routes/app.copilot'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRoleRoute = AuthRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFaceRoute = AuthFaceRouteImport.update({
  id: '/face',
  path: '/face',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsRoute = AppLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppInsuranceRoute = AppInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppGraphRoute = AppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/graph': typeof AppGraphRoute
  '/app/help': typeof AppHelpRoute
  '/app/insurance': typeof AppInsuranceRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/lessons': typeof AppLessonsRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quality': typeof AppQualityRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/face': typeof AuthFaceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/verify': typeof AuthVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/graph': typeof AppGraphRoute
  '/app/help': typeof AppHelpRoute
  '/app/insurance': typeof AppInsuranceRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/lessons': typeof AppLessonsRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quality': typeof AppQualityRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/face': typeof AuthFaceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/verify': typeof AuthVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/graph': typeof AppGraphRoute
  '/app/help': typeof AppHelpRoute
  '/app/insurance': typeof AppInsuranceRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/lessons': typeof AppLessonsRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/quality': typeof AppQualityRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/face': typeof AuthFaceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/verify': typeof AuthVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/contact'
    | '/app/analytics'
    | '/app/copilot'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/graph'
    | '/app/help'
    | '/app/insurance'
    | '/app/inventory'
    | '/app/knowledge'
    | '/app/lessons'
    | '/app/maintenance'
    | '/app/notifications'
    | '/app/profile'
    | '/app/quality'
    | '/app/settings'
    | '/auth/face'
    | '/auth/login'
    | '/auth/role'
    | '/auth/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/contact'
    | '/app/analytics'
    | '/app/copilot'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/graph'
    | '/app/help'
    | '/app/insurance'
    | '/app/inventory'
    | '/app/knowledge'
    | '/app/lessons'
    | '/app/maintenance'
    | '/app/notifications'
    | '/app/profile'
    | '/app/quality'
    | '/app/settings'
    | '/auth/face'
    | '/auth/login'
    | '/auth/role'
    | '/auth/verify'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/contact'
    | '/app/analytics'
    | '/app/copilot'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/graph'
    | '/app/help'
    | '/app/insurance'
    | '/app/inventory'
    | '/app/knowledge'
    | '/app/lessons'
    | '/app/maintenance'
    | '/app/notifications'
    | '/app/profile'
    | '/app/quality'
    | '/app/settings'
    | '/auth/face'
    | '/auth/login'
    | '/auth/role'
    | '/auth/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/role': {
      id: '/auth/role'
      path: '/role'
      fullPath: '/auth/role'
      preLoaderRoute: typeof AuthRoleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/face': {
      id: '/auth/face'
      path: '/face'
      fullPath: '/auth/face'
      preLoaderRoute: typeof AuthFaceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quality': {
      id: '/app/quality'
      path: '/quality'
      fullPath: '/app/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/maintenance': {
      id: '/app/maintenance'
      path: '/maintenance'
      fullPath: '/app/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lessons': {
      id: '/app/lessons'
      path: '/lessons'
      fullPath: '/app/lessons'
      preLoaderRoute: typeof AppLessonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insurance': {
      id: '/app/insurance'
      path: '/insurance'
      fullPath: '/app/insurance'
      preLoaderRoute: typeof AppInsuranceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/graph': {
      id: '/app/graph'
      path: '/graph'
      fullPath: '/app/graph'
      preLoaderRoute: typeof AppGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppGraphRoute: typeof AppGraphRoute
  AppHelpRoute: typeof AppHelpRoute
  AppInsuranceRoute: typeof AppInsuranceRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppLessonsRoute: typeof AppLessonsRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQualityRoute: typeof AppQualityRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppGraphRoute: AppGraphRoute,
  AppHelpRoute: AppHelpRoute,
  AppInsuranceRoute: AppInsuranceRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppLessonsRoute: AppLessonsRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppQualityRoute: AppQualityRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthFaceRoute: typeof AuthFaceRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRoleRoute: typeof AuthRoleRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthFaceRoute: AuthFaceRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRoleRoute: AuthRoleRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
